keys:
  - &primary age1sseqwwa7fc0ftry8njyuagdg28fkmtdwmj6m7p3etjsj83suee3shfzjyz
creation_rules:
  - path_regex: secrets/battleship-secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: secrets/battleship-secrets.lesser.json$
    key_groups:
      - age:
        - *primary
  - path_regex: secrets/spacestation-secrets.yaml$
    key_groups:
      - age:
        - *primary
  - path_regex: secrets/spacestation-secrets.lesser.json$
    key_groups:
      - age:
        - *primary
